//ADMIN TYPES
//loaders
export const ADMIN_LOGIN_ENABLE_LOADER = 'ADMIN_LOGIN_ENABLE_LOADER';
export const ADMIN_LOGIN_DISABLE_LOADER = 'ADMIN_LOGIN_DISABLE_LOADER';

// login
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_RESPONSE = 'ADMIN_LOGIN_RESPONSE';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOG_OUT = 'ADMIN_LOG_OUT';
export const ADMIN_LOGIN_LOADING_ENDED = 'ADMIN_LOGIN_LOADING_ENDED';
