//ADMIN TYPES
//loaders
export const COMPETITION_ENABLE_LOADER = 'COMPETITION_ENABLE_LOADER';
export const COMPETITION_DISABLE_LOADER = 'COMPETITION_DISABLE_LOADER';

// competions
export const COMPETITION_REQUEST = 'COMPETITION_REQUEST';
export const COMPETITION_RESPONSE = 'COMPETITION_RESPONSE';
export const COMPETITION_FAILED = 'COMPETITION_FAILED';
export const COMPETITION_LOADING_ENDED = 'COMPETITION_LOADING_ENDED';
