//ADMIN TYPES
//loaders
export const LOGIN_ENABLE_LOADER = 'ADMIN_LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'ADMIN_LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'ADMIN_LOGIN_RESPONSE';
export const LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const LOG_OUT = 'ADMIN_LOG_OUT';
export const LOGIN_LOADING_ENDED = 'ADMIN_LOGIN_LOADING_ENDED';
